apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.github: |
    token: $github-privateKey

  trigger.on-sync-succeeded: |
    when: app.status.operationState.phase in ['Succeeded']
    send:
    - github-notify

  template.github-notify: |
    message: |
      ✅ App {{.app.metadata.name}} synced to revision {{.app.status.sync.revision}}.
    github:
      repoURL: https://github.com/faizulkhan56/argocd-app2
      status:
        state: success
        label: argo-cd/sync
        targetURL: http://18.234.68.168:31497/applications/{{.app.metadata.name}}
        description: Argo CD sync succeeded
