apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/faizulkhan56/gitops-infra.git
    targetRevision: HEAD
    path: ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: test1         # Or whatever namespace your IngressController watches
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

